from __future__ import annotations
from typing import Protocol


class DiscordService(Protocol):
    def send_embed(self, channel_id: str, embed: dict) -> str: ...
    def assign_role(self, guild_id: str, member_id: str, role_id: str) -> None: ...
    def remove_role(self, guild_id: str, member_id: str, role_id: str) -> None: ...
